### ISSUE TITLE
Need Data

### ISSUE THREAD

**Issue by AMEERAZAM08** [SrLozano/Tinder-Big-Data-Analysis#1]
Hi Lozano, I am a student of Hyderabad University, looking to complete my natural Language Processing course with a term project in Dating conversation generation. I have known about you from your Tinder Big-Data analysis project.

I have been searching for a dataset for my project which contains conversations between two people who are dating. Can you please help me in my project? It would be really helpful if you could share any dating conversation data. I don't need any personal information if it is a concern.

My email id is: 20mcmi18@uohyd.ac.in

Thanks a lot for your help

**Comment by SrLozano** [comment]
Hi Ameer. I got the dataset from https://www.swipestats.io/. It was made by a guy from Norway and his business model is to charge for the data. So I am not allowed to give it to you for free since it is unfair to him. Nevertheless he has no troubles giving the dataset for free for academic purposes like it is my case. 

So write to him and explain your situation so he decides whether to send it to you for free or not. 

Have a nice day.

**Comment by AMEERAZAM08** [comment]
Can you email me contact of that person ?

**Comment by SrLozano** [comment]
There you have! 

https://no.linkedin.com/in/kristianeboe

Good luck with your project! 🍀🤞🏼
