### ISSUE TITLE
could you provide the data

### ISSUE THREAD

**Issue by angeljoshy005** [SrLozano/Tinder-Big-Data-Analysis#2]

**Comment by SrLozano** [comment]
Hi! I got the dataset from https://www.swipestats.io/. It was made by a guy from Norway and his business model is to charge for the data. So I am not allowed to give it to you for free since it is unfair to him. Nevertheless he has no troubles giving the dataset for free for academic purposes. 

So write to him and explain your situation so he decides whether to send it to you for free or not. 

Have a nice day
